#
# CS3099 Group A3
#

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies
  
  - package-ecosystem: "bundler"
    open-pull-requests-limit: 0
    directory: "/docs"
    schedule:
      interval: "daily"
    labels:
      - dependencies
