codecov:
  allow_coverage_offsets: true

coverage:
  status:
    project:
      default:
        informational: true
        only_pulls: true
    patch:
      default:
        informational: true
        only_pulls: true

comment:
  layout: "reach, diff, flags"

ignore:
  - "**/scripts/"
