packageExtensions:
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  "@graphql-modules/core@*":
    peerDependencies:
      reflect-metadata: "*"
  react-scripts@*:
    peerDependencies:
      sass: ^1.3.0
  winston-transport@*:
    dependencies:
      logform: ^2.2.0
  "@accounts/graphql-api@*":
    dependencies:
      graphql: 14.6.0
    peerDependencies:
      "@accounts/types": ^0.30.0
  "@accounts/mongo@*":
    dependencies:
      "@types/mongodb": 3.5.33
  "@accounts/password@*":
    dependencies:
      "@accounts/types": ^0.30.0
  subscriptions-transport-ws@*:
    dependencies:
      "@types/ws": ^5.1.2


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
