packageExtensions:
  "@accounts/mongo-password@*":
    peerDependencies:
      mongodb: ^3.4.1
  "@accounts/mongo-sessions@*":
    peerDependencies:
      mongodb: ^3.4.1
  "@accounts/mongo@*":
    dependencies:
      "@types/mongodb": 3.5.33
  "@accounts/password@*":
    dependencies:
      "@accounts/types": ^0.30.0
  "@apollo/protobufjs@*":
    peerDependencies:
      "@types/long": 4.0.0
      long: ^4.0.0
  "@graphql-modules/core@*":
    peerDependencies:
      reflect-metadata: "*"
  apollo-reporting-protobuf@*:
    dependencies:
      "@types/long": 4.0.0
      long: ^4.0.0
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  react-scripts@*:
    peerDependencies:
      sass: ^1.3.0
  subscriptions-transport-ws@*:
    dependencies:
      "@types/ws": ^5.1.2
  winston-transport@*:
    dependencies:
      logform: ^2.2.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
