#
# CS3099 Group A3
#

FROM node:12-alpine
WORKDIR /usr/src/unifed
COPY yarn.lock .
COPY package.json .
COPY packages/shared/package.json packages/shared/package.json
COPY packages/frontend/package.json packages/frontend/package.json
RUN yarn install
ADD packages packages
ENV CI=true
CMD [ "yarn", "workspace", "unifed-frontend", "start" ]
EXPOSE 3000
