#
# CS3099 Group A3
#

SHELL:=/bin/bash

DOCKER_COMPOSE_COMMAND:=docker-compose \
	--env-file configs/config.env \
  -f <(./scripts/generate-docker-compose) \
  --project-directory .

.PHONY: start
start:
	$(DOCKER_COMPOSE_COMMAND) up --build -d

.PHONY: stop
stop:
	$(DOCKER_COMPOSE_COMMAND) stop

.PHONY: reset
reset:
	$(DOCKER_COMPOSE_COMMAND) down --remove-orphans --volumes

.PHONY: logs
logs:
	$(DOCKER_COMPOSE_COMMAND) logs
