#
# CS3099 Group A3
#

apiVersion: v1
kind: Pod

metadata:
  name: unifed
  creationTimestamp: "2020-10-17T17:49:13Z"

spec:
  restartPolicy: OnFailure

  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
      - "backend-internal"
      - "backend-federation"
      - "frontend"
      - "mongo"

  containers:
    - name: mongo
      image: docker.io/library/mongo:4
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          name: mongo-init
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ${MONGO_ADMIN_USERNAME}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: ${MONGO_ADMIN_PASSWORD}
    
    - name: nginx
      image: docker.io/corfr/nginx-dnsmasq
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
      ports:
        - containerPort: 80
          hostPort: ${BACKEND_PORT}
          protocol: TCP
  
    - name: mongo-express
      image: docker.io/library/mongo-express
      ports:
        - containerPort: 8081
          hostPort: ${MONGO_INSPECT_PORT}
          protocol: TCP
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: ${MONGO_ADMIN_USERNAME}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: ${MONGO_ADMIN_PASSWORD}
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: ${MONGO_INSPECT_USERNAME} 
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: ${MONGO_INSPECT_PASSWORD}
  
    - name: backend-internal
      image: localhost/unifed-backend-internal
      volumeMounts:
        - mountPath: /usr/src/unifed/packages/backend-internal-server/src
          name: backend-internal-server
        - mountPath: /usr/src/unifed/packages/backend-core/src
          name: backend-core
        - mountPath: /usr/src/unifed/packages/backend-federation-client/src
          name: backend-federation-client
        - mountPath: /usr/src/unifed/packages/shared/src
          name: shared
      env:
        - name: UNIFED_SMTP_USERNAME
          value: ${SMTP_USERNAME}
        - name: UNIFED_SMTP_PASSWORD
          value: ${SMTP_PASSWORD}
        - name: UNIFED_SMTP_HOST
          value: ${SMTP_HOST}
        - name: UNIFED_SMTP_PORT
          value: ${SMTP_PORT}
        - name: UNIFED_MONGO_HOSTNAME
          value: mongo
        - name: UNIFED_MONGO_PORT
          value: 27017
        - name: UNIFED_MONGO_DATABASE
          value: unifed-internal
        - name: UNIFED_MONGO_USERNAME
          value: user
        - name: UNIFED_MONGO_PASSWORD
          value: pass
        - name: UNIFED_JWT_SECRET
          value: ${JWT_SECRET}
        - name: UNIFED_SITE_HOST
          value: ${SITE_HOST}
        - name: UNIFED_SITE_PROTOCOL
          value: ${SITE_PROTOCOL}
        - name: UNIFED_APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: UNIFED_LOGGING_LEVEL
          value: ${LOGGING_LEVEL}
        - name: UNIFED_SERVER_PORT
          value: 7080
        - name: NODE_ENV
          value: ${NODE_ENV}

    - name: backend-federation
      image: localhost/unifed-backend-federation
      volumeMounts:
        - mountPath: /usr/src/unifed/packages/backend-federation-server/src
          name: backend-federation-server
        - mountPath: /usr/src/unifed/packages/backend-core/src
          name: backend-core
        - mountPath: /usr/src/unifed/packages/shared/src
          name: shared
      env:
        - name: UNIFED_MONGO_HOSTNAME
          value: mongo
        - name: UNIFED_MONGO_PORT
          value: 27017
        - name: UNIFED_MONGO_DATABASE
          value: unifed-federation
        - name: UNIFED_MONGO_USERNAME
          value: user
        - name: UNIFED_MONGO_PASSWORD
          value: pass
        - name: UNIFED_SITE_HOST
          value: ${SITE_HOST}
        - name: UNIFED_SITE_PROTOCOL
          value: ${SITE_PROTOCOL}
        - name: UNIFED_APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: UNIFED_LOGGING_LEVEL
          value: ${LOGGING_LEVEL}
        - name: UNIFED_SERVER_PORT
          value: 7081
        - name: NODE_ENV
          value: ${NODE_ENV}
    
    - name: frontend
      image: localhost/unifed-frontend
      volumeMounts:
        - mountPath: /usr/src/unifed/packages/frontend/src
          name: frontend
        - mountPath: /usr/src/unifed/packages/shared/src
          name: shared

  volumes:
    - name: frontend
      hostPath:
        path: ./packages/frontend/src
        type: Directory

    - name: shared
      hostPath:
        path: ./packages/shared/src
        type: Directory

    - name: backend-internal-server
      hostpath:
        path: ./packages/backend-internal-server/src
        type: Directory
    
    - name: backend-federation-server
      hostpath:
        path: ./packages/backend-federation-server/src
        type: Directory

    - name: backend-federation-client
      hostpath:
        path: ./packages/backend-federation-client/src
        type: Directory

    - name: backend-core
      hostpath:
        path: ./packages/backend-core/src
        type: Directory
    
    - name: nginx-conf
      hostpath:
        path: ./configs/nginx.dev.conf
        type: File
    
    - name: mongo-init
      hostpath:
        path: ./configs/mongo-init.js
        type: File
