#!/usr/bin/env bash
#
# Copyright (C) 2021 Kian Cross
#
# This file is part of Unifed.
#
# Unifed is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Unifed is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Unifed.  If not, see <https://www.gnu.org/licenses/>.
#

# Script used to generate the developer documentation.
# This includes creating a clone of the README.md file
# and programmatically editing slightly.

set -e

README="README.md"
DOCS_README="docs/_README.md"

# Add custom styles to the README used in developer documentation.
echo '<style> .tsd-typography ul ul { margin: 0 !important; } </style>' > "$DOCS_README"

cat "$README" | sed -e '2,5d' >> $DOCS_README

yarn typedoc
