#
# CS3099 Group A3
#

name: School GitLab Mirror

on:
  schedule:
    # Everyday at 6am
    - cron:  "0 6 */1 * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@eac5c75eb35c3335d2439c9a208c75a949077772
      with:
        target_repo_url: git@gitlab.cs.st-andrews.ac.uk:cs3099group-a3/project-code.git
        ssh_private_key: ${{ secrets.SCHOOL_GITLAB_SSH_KEY }}
