#
# CS3099 Group A3
#

name: Checks

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  checks:
    name: ${{ matrix.component }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend, shared]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - run: npm install -g yarn
      - run: yarn install

      - name: Style checks
        run: yarn workspace unifed-${{ matrix.component }} lint
      
      - name: Build
        run: yarn workspace unifed-${{ matrix.component }} build
      
      - name: Unit tests
        run: yarn workspace unifed-${{ matrix.component }} test:unit
  
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: checks
    env:
      NODE_ENV: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - run: npm install -g yarn
      - run: yarn install
      - run: yarn workspace unifed-frontend build

      - run: make -f Makefile.docker start

      - name: Frontend integration tests
        run: yarn workspace unifed-frontend run test:integration
        continue-on-error: true
      
      - name: Backend integration tests
        run: yarn workspace unifed-frontend run test:integration
        continue-on-error: true

      - run: make -f Makefile.docker stop
